export const LOGIN_SUCCESS: string = "LOGIN_SUCCESS";
export const LOGIN_FAIL: string = "LOGIN_FAIL";
export const LOGIN_REQUEST: string = "LOGIN_REQUEST";

export const REGISTER_SUCCESS: string = "REGISTER_SUCCESS";
export const REGISTER_FAIL: string = "REGISTER_FAIL";
export const REGISTER_REQUEST: string = "REGISTER_REQUEST";

export const LOAD_USER_SUCCESS: string = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL: string = "LOAD_USER_FAIL";
export const LOAD_USER_REQUEST: string = "LOAD_USER_REQUEST";

export const ALL_USERS_REQUEST: string = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS: string = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL: string = "ALL_USERS_FAIL";

export const POST_OF_FOLLOWING_REQUEST: string = "POST_OF_FOLLOWING_REQUEST";
export const POST_OF_FOLLOWING_SUCCESS: string = "POST_OF_FOLLOWING_SUCCESS";
export const POST_OF_FOLLOWING_FAIL: string = "POST_OF_FOLLOWING_FAIL";

export const CLEAR_ERRORS: string = "CLEAR_ERRORS";

export const LOGOUT_REQUEST: string = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: string = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL: string = "LOGOUT_FAIL";

export const DELETE_PROFILE_REQUEST: string = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS: string = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL: string = "DELETE_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST: string = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS: string = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL: string = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST: string = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS: string = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL: string = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST: string = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS: string = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL: string = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST: string = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: string = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL: string = "RESET_PASSWORD_FAIL";

export const USER_POSTS_REQUEST: string = "USER_POSTS_REQUEST";
export const USER_POSTS_SUCCESS: string = "USER_POSTS_SUCCESS";
export const USER_POSTS_FAIL: string = "USER_POSTS_FAIL";

export const GET_USER_PROFILE_REQUEST: string = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS: string = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL: string = "GET_USER_PROFILE_FAIL";
